In [58]:
import numpy as np
import pandas as pd

In [59]:
df=pd.read_csv(r"Downloads/anime.csv")

In [60]:
df.head() ## top 5 rows

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [ ]:
## Extracting number of episodes in an anime

In [61]:
def extract_episodes(txt):
    check=False
    data=""
    for i in txt:
        if i==")":
            check=False 
            break
        if i=="(":
            check=True
            continue
        if check==True:
            data+=i
    return data

In [121]:
df["Episodes"]=df["Title"].apply(extract_episodes)
df.head()

,Rank,Title,Score,Episodes,Time-Stamp,Running-Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64 eps,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24 eps,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13 eps,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51 eps,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10 eps,Apr 2019 - Jul 2019,3

In [ ]:
## Converting the whole Episode string  to int

In [63]:
def removeeps(txt):
    data=""
    for i in txt:
        if(i==" "):
            break
        data+=i    
    return data

In [122]:
df['Episodes']=df['Episodes'].apply(removeeps)
# or you can do this 
df['Episodes']=df["Episodes"].str.replace(" eps","")
df["Episodes"]=df['Episodes'].astype(int)
df.head()

,Rank,Title,Score,Episodes,Time-Stamp,Running-Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [ ]:
## Extracting Time stamp from the title

In [72]:
def extract_timestamp(txt):
    data=''
    for i in range(len(txt)):
        if txt[i]==')':
            for j in range(i+1,i+1+19):
                data+=txt[j]
            break
    return data

In [123]:
df['Time-Stamp']=df["Title"].apply(extract_timestamp)
df.head()

,Rank,Title,Score,Episodes,Time-Stamp,Running-Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [80]:
## Anime with highest score

In [85]:
highest=df["Score"].max()
df["Title"][df['Score']==highest]
## or we can do this
df['Title'][df['Score']==df['Score'].max()]

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

In [86]:
## Displaying top 5 anime title

In [94]:
df[["Title",'Score']].head()

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [95]:
## highest episode count

In [96]:
df[['Title','Episodes']][df['Episodes']==df['Episodes'].max()]

                                                Title  Episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201

In [ ]:
## top 5 episode count

In [109]:
df.sort_values(by="Episodes",ascending=False).head()
# or we can use 
df.nlargest(5,"Episodes")[["Title","Episodes"]]

                                                Title  Episodes
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201
7   Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...       148
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110
42  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...        75
24  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...        74

In [110]:
## count number of month in each anime

In [111]:
def get_months(time_stamp):
    try:
        start, end = time_stamp.split(" - ")
        start = pd.to_datetime(start)
        end = pd.to_datetime(end)
        
        months = (end.year - start.year) * 12 + (end.month - start.month)
        return months
    except:
        return None

In [117]:
df['Running-Months']=df['Time-Stamp'].apply(get_months)
df.head()

,Rank,Title,Score,Episodes,Time-Stamp,Running-Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [116]:
## longest running anime

In [119]:
df[['Title','Running-Months']][df['Running-Months']== df['Running-Months'].max()]

                                                Title  Running-Months
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...             110

In [124]:
df.head()

,Rank,Title,Score,Episodes,Time-Stamp,Running-Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3